spring.application.name=tipo-cambio-api

spring.datasource.url=jdbc:postgresql://localhost:5432/fx_prueba
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.main.banner-mode=off